name: Performance Regression

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  benchmark:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            label: cpu
          - runner: ubuntu-latest
            label: gpu
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r tests/requirements-test.txt

      - name: Run performance smoke tests
        run: |
          mkdir -p perf-results
          pytest tests/test_gpu_kernel_unit.py \
            --perf-log perf-results/${{ matrix.label }}.json \
            --perf-threshold gemv_tokens_per_second=1.0 || true

      - name: Upload performance artifacts
        uses: actions/upload-artifact@v4
        with:
          name: perf-${{ matrix.label }}
          path: perf-results
          if-no-files-found: warn
